# Generated by Django 4.2.4 on 2023-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("won", "Korean Won"), ("usd", "Dollar"), ("euro", "Euro")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("animal", "Animal"),
                    ("things", "Things"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("kr", "Korean"),
                    ("en", "English"),
                    ("cn", "Chinese"),
                    ("jp", "Japanese"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_pciture",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
