# Generated by Django 4.2.4 on 2023-08-25 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_currency_user_gender_user_language_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_pciture",
            new_name="profile_picture",
        ),
    ]
