# Generated by Django 4.2.4 on 2023-08-25 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="rate",
            new_name="rating",
        ),
    ]
