# Generated by Django 4.2.4 on 2023-08-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_initial"),
        ("experiences", "0002_initial"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="owner",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="experiences",
            field=models.ManyToManyField(
                blank=True, null=True, to="experiences.experience"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(blank=True, null=True, to="rooms.room"),
        ),
    ]
