# Generated by Django 4.2.4 on 2023-08-27 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="check_out_data",
            new_name="check_out_date",
        ),
    ]
